In [1]:
import os
import pandas as pd
import cv2
import numpy as np
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.preprocessing.image import img_to_array, load_img
from matplotlib import pyplot as plt
from collections import Counter
from sklearn.model_selection import train_test_split
from tensorflow.keras.applications import ResNet50, EfficientNetB0, InceptionV3, DenseNet121, Xception
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout, BatchNormalization
from tensorflow.keras.models import Model
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam
import tensorflow as tf
from script import process_df_for_resnet, plot_image_with_predictions, create_model, get_top_predictions, custom_train_loop

In [2]:
big_csv_path = "2_preprocessed_sequences_with_interpolation_v0.csv"
df_big = pd.read_csv(big_csv_path)
df_big.columns

Index(['Unnamed: 0', 'Extracted_Datetime', 'Dataset_prefix_group_id',
       'Rel_Image_Path', 'Rel_Label_Path', 'Image_basename', 'Label_basename',
       'Origin_dataset_name', 'Datetime_Str', 'Extension', 'Date', 'Time',
       'Year', 'Month', 'Day', 'Hour', 'Minute', 'Second', 'img_height',
       'img_width', 'has_label', 'yolo_bbox_xcenter', 'yolo_bbox_ycenter',
       'yolo_bbox_width', 'yolo_bbox_height', 'new_label', 'pred',
       'nb_detections'],
      dtype='object')

In [3]:
csv_path = "shuffled_DS_fp_subset_enlarged_classes.csv"
df = pd.read_csv(csv_path)

In [4]:
df["Image_basename"] = [os.path.basename(path) for path in df.img_rel_path]
df.head()

,img_rel_path,label_rel_path,has_label_file,category_label,detection_label,environment_label,Image_basename
0,images/pyronear_salaunes_1_1_2023_08_09T18_11_...,labels/pyronear_salaunes_1_1_2023_08_09T18_11_...,True,nuagesbas,['nuagesbas'],[],pyronear_salaunes_1_1_2023_08_09T18_11_59.jpg
1,images/pyronear_courmettes_1_2023_11_07T14_03_...,labels/pyronear_courmettes_1_2023_11_07T14_03_...,True,nuagesbas,['nuagesbas'],[],pyronear_courmettes_1_2023_11_07T14_03_17.jpg
2,images/pyronear_brison_3_2023_08_29T06_13_44.jpg,labels/pyronear_brison_3_2023_08_29T06_13_44.txt,True,montagne,['montagne'],[],pyronear_brison_3_2023_08_29T06_13_44.jpg
3,images/pyronear_valbonne_2_2023_11_05T15_54_38...,labels/pyronear_valbonne_2_2023_11_05T15_54_38...,True,nuagesbas,['nuagesbas'],[],pyronear_valbonne_2_2023_11_05T15_54_38.jpg
4,images/pyronear_marguerite_1_2023_09_16T12_39_...,labels/pyronear_marguerite_1_2023_09_16T12_39_...,True,nuagesbas,['nuagesbas'],[],pyronear_marguerite_1_2023_09_16T12_39_29.jpg

In [5]:
df_bbox = df_big.copy()
df_bbox = df_bbox[['Image_basename', 'yolo_bbox_xcenter', 'yolo_bbox_ycenter','yolo_bbox_width', 'yolo_bbox_height', 'nb_detections']]
df_bbox.head()

,Image_basename,yolo_bbox_xcenter,yolo_bbox_ycenter,yolo_bbox_width,yolo_bbox_height,nb_detections
0,ADF_1320_2023_05_23T17_18_31.jpg,0.443542,0.329634,0.024021,0.036620,1.0
1,ADF_1320_2023_05_23T17_19_01.jpg,0.445935,0.332069,0.016495,0.024454,1.0
2,ADF_1320_2023_05_23T17_19_31.jpg,0.435669,0.335111,0.038391,0.032963,1.0
3,ADF_1320_2023_05_23T17_20_01.jpg,0.443198,0.327810,0.017865,0.028102,1.0
4,ADF_1320_2023_05_23T17_20_01.jpg,0.443198,0.327810,0.017865,0.028102,1.0

In [6]:
final_df = pd.merge(df, df_bbox, on='Image_basename', how='inner')
final_df

,img_rel_path,label_rel_path,has_label_file,category_label,detection_label,environment_label,Image_basename,yolo_bbox_xcenter,yolo_bbox_ycenter,yolo_bbox_width,yolo_bbox_height,nb_detections
0,images/pyronear_salaunes_1_1_2023_08_09T18_11_...,labels/pyronear_salaunes_1_1_2023_08_09T18_11_...,True,nuagesbas,['nuagesbas'],[],pyronear_salaunes_1_1_2023_08_09T18_11_59.jpg,0.977803,0.470367,0.044394,0.115933,1.0
1,images/pyronear_courmettes_1_2023_11_07T14_03_...,labels/pyronear_courmettes_1_2023_11_07T14_03_...,True,nuagesbas,['nuagesbas'],[],pyronear_courmettes_1_2023_11_07T14_03_17.jpg,0.160458,0.491901,0.139662,0.065403,1.0
2,images/pyronear_courmettes_1_2023_11_07T14_03_...,labels/pyronear_courmettes_1_2023_11_07T14_03_...,True,nuagesbas,['nuagesbas'],[],pyronear_courmettes_1_2023_11_07T14_03_17.jpg,0.160458,0.491901,0.139662,0.065403,1.0
3,images/pyronear_courmettes_1_2023_11_07T14_03_...,labels/pyronear_courmettes_1_2023_11_07T14_03_...,True,nuagesbas,['nuagesbas'],[],pyronear_courmettes_1_2023_11_07T14_03_17.jpg,0.160458,0.491901,0.139662,0.065403,1.0
4,images/pyronear_brison_3_2023_08_29T06_13_44.jpg,labels/pyronear_brison_3_2023_08_29T06_13_44.txt,True,montagne,['montagne'],[],pyronear_brison_3_2023_08_29T06_13_44.jpg,0.451882,0.597144,0.054057,0.048884,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
12318,images/pyronear_salaunes_2_1_2023_08_28T18_29_...,labels/pyronear_salaunes_2_1_2023_08_28T18_29_...,True,grosnuages,['grosnuagesrefletssoleil'],[],pyronear_salaunes_2_1_2023_08_28T18_29_29.jpg,0.155722,0.203692,0.311443,0.404528,1.0
12319,images/pyronear_valbonne_4_2023_10_30T15_35_00...,labels/pyronear_valbonne_4_2023_10_30T15_35_00...,True,nuagesbas,['nuagesbas'],[],pyronear_valbonne_4_2023_10_30T15_35_00.jpg,0.408868,0.555045,0.018049,0.024031,1.0
12320,images/pyronear_valbonne_4_2023_11_02T08_56_06...,labels/pyronear_valbonne_4_2023_11_02T08_56_06...,True,nuagesbas,['nuagesbas'],[],pyronear_valbonne_4_2023_11_02T08_56_06.jpg,0.424089,0.586755,0.043256,0.043289,1.0
12321,images/pyronear_ferion_2_2023_10_17T14_34_06.jpg,labels/pyronear_ferion_2_2023_10_17T14_34_06.txt,True,nuagesbas,['nuagesbas'],['brume'],pyronear_ferion_2_2023_10_17T14_34_06.jpg,0.964625,0.520038,0.070750,0.197814,1.0
12322,images/pyronear_cabanelle_1_2023_10_11T14_59_2...,labels/pyronear_cabanelle_1_2023_10_11T14_59_2...,True,brume,['brume'],[],pyronear_cabanelle_1_2023_10_11T14_59_29.jpg,0.160976,0.460071,0.169219,0.264838,1.0

In [9]:
final_df.head()

,img_rel_path,label_rel_path,has_label_file,category_label,detection_label,environment_label,Image_basename,yolo_bbox_xcenter,yolo_bbox_ycenter,yolo_bbox_width,yolo_bbox_height,nb_detections
0,images/pyronear_salaunes_1_1_2023_08_09T18_11_...,labels/pyronear_salaunes_1_1_2023_08_09T18_11_...,True,nuagesbas,['nuagesbas'],[],pyronear_salaunes_1_1_2023_08_09T18_11_59.jpg,0.977803,0.470367,0.044394,0.115933,1.0
1,images/pyronear_courmettes_1_2023_11_07T14_03_...,labels/pyronear_courmettes_1_2023_11_07T14_03_...,True,nuagesbas,['nuagesbas'],[],pyronear_courmettes_1_2023_11_07T14_03_17.jpg,0.160458,0.491901,0.139662,0.065403,1.0
2,images/pyronear_courmettes_1_2023_11_07T14_03_...,labels/pyronear_courmettes_1_2023_11_07T14_03_...,True,nuagesbas,['nuagesbas'],[],pyronear_courmettes_1_2023_11_07T14_03_17.jpg,0.160458,0.491901,0.139662,0.065403,1.0
3,images/pyronear_courmettes_1_2023_11_07T14_03_...,labels/pyronear_courmettes_1_2023_11_07T14_03_...,True,nuagesbas,['nuagesbas'],[],pyronear_courmettes_1_2023_11_07T14_03_17.jpg,0.160458,0.491901,0.139662,0.065403,1.0
4,images/pyronear_brison_3_2023_08_29T06_13_44.jpg,labels/pyronear_brison_3_2023_08_29T06_13_44.txt,True,montagne,['montagne'],[],pyronear_brison_3_2023_08_29T06_13_44.jpg,0.451882,0.597144,0.054057,0.048884,1.0

In [10]:
label_category= "grosnuage"

In [11]:
X, y, category_mapping = process_df_for_resnet(final_df.head(7500), min_num=1, label_cat=label_category)

too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat
too much hors cat

In [12]:
X[0].shape

(224, 224, 3)

In [13]:
print(len(y))
y

1633

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 ...]

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
model_name = "inceptionv3"
print("Creating model ...")
model = create_model(backbone_name=model_name, num_classes=1)

print("Starting training...")
num_epochs = 5
model = custom_train_loop(model, X_train, y_train, X_test, y_test, num_epochs=num_epochs, batch_size=4, learning_rate=0.001)

model.save(f"test_{model_name}_{label_category}_equilibrate.h5")
model.save_weights(f"test_{model_name}_{label_category}_equilibrate.weights.h5")

# evaluate_model(model, X_test, y_test)

print("Displaying predictions...")
#display_predictions(model, X_test, y_test, category_mapping)
print("End.")

Creating model ...
Starting training...

Epoch 1/5
  Batch 10: Loss = 0.7373, Accuracy = 0.6750
  Batch 20: Loss = 0.8411, Accuracy = 0.6375
  Batch 30: Loss = 0.8301, Accuracy = 0.6333
  Batch 40: Loss = 0.7588, Accuracy = 0.6562
  Batch 50: Loss = 0.7404, Accuracy = 0.6650
  Batch 60: Loss = 0.7503, Accuracy = 0.6458
  Batch 70: Loss = 0.7087, Accuracy = 0.6786
  Batch 80: Loss = 0.6869, Accuracy = 0.6844
  Batch 90: Loss = 0.6875, Accuracy = 0.6750
  Batch 100: Loss = 0.6757, Accuracy = 0.6875
  Batch 110: Loss = 0.6672, Accuracy = 0.6795
  Batch 120: Loss = 0.6583, Accuracy = 0.6833
  Batch 130: Loss = 0.6535, Accuracy = 0.6885
  Batch 140: Loss = 0.6471, Accuracy = 0.6946
  Batch 150: Loss = 0.6444, Accuracy = 0.6867
  Batch 160: Loss = 0.6425, Accuracy = 0.6844
  Batch 170: Loss = 0.6432, Accuracy = 0.6750
  Batch 180: Loss = 0.6415, Accuracy = 0.6736
  Batch 190: Loss = 0.6393, Accuracy = 0.6737
  Batch 200: Loss = 0.6267, Accuracy = 0.6800
  Batch 210: Loss = 0.6254, Accuracy = 0.6810
  Batch 220: Loss = 0.6216, Accuracy = 0.6841
  Batch 230: Loss = 0.6221, Accuracy = 0.6826
  Batch 240: Loss = 0.6133, Accuracy = 0.6885
  Batch 250: Loss = 0.6142, Accuracy = 0.6900
  Batch 260: Loss = 0.6236, Accuracy = 0.6837
  Batch 270: Loss = 0.6207, Accuracy = 0.6880
  Batch 280: Loss = 0.6207, Accuracy = 0.6884
  Batch 290: Loss = 0.6243, Accuracy = 0.6853
  Batch 300: Loss = 0.6200, Accuracy = 0.6867
  Batch 310: Loss = 0.6195, Accuracy = 0.6855
  Batch 320: Loss = 0.6176, Accuracy = 0.6867

Epoch 1 Summary:
  Train Loss: 0.6227, Train Accuracy: 0.6845
  Test Loss: 1.5120, Test Accuracy: 0.7003

Epoch 2/5
  Batch 10: Loss = 0.5328, Accuracy = 0.7250
  Batch 20: Loss = 0.6752, Accuracy = 0.6500
  Batch 30: Loss = 0.6826, Accuracy = 0.6500
  Batch 40: Loss = 0.7097, Accuracy = 0.6250
  Batch 50: Loss = 0.6746, Accuracy = 0.6450
  Batch 60: Loss = 0.6860, Accuracy = 0.6250
  Batch 70: Loss = 0.6654, Accuracy = 0.6429
  Batch 80: Loss = 0.6523, Accuracy = 0.6594
  Batch 90: Loss = 0.6389, Accuracy = 0.6639
  Batch 100: Loss = 0.6500, Accuracy = 0.6625
  Batch 110: Loss = 0.6432, Accuracy = 0.6682
  Batch 120: Loss = 0.6419, Accuracy = 0.6667
  Batch 130: Loss = 0.6468, Accuracy = 0.6615
  Batch 140: Loss = 0.6393, Accuracy = 0.6607
  Batch 150: Loss = 0.6372, Accuracy = 0.6633
  Batch 160: Loss = 0.6413, Accuracy = 0.6578
  Batch 170: Loss = 0.6335, Accuracy = 0.6603
  Batch 180: Loss = 0.6288, Accuracy = 0.6625
  Batch 190: Loss = 0.6257, Accuracy = 0.6645
  Batch 200: Loss = 0.6209, Accuracy = 0.6662
  Batch 210: Loss = 0.6174, Accuracy = 0.6679
  Batch 220: Loss = 0.6161, Accuracy = 0.6682
  Batch 230: Loss = 0.6195, Accuracy = 0.6663
  Batch 240: Loss = 0.6156, Accuracy = 0.6677
  Batch 250: Loss = 0.6163, Accuracy = 0.6690
  Batch 260: Loss = 0.6190, Accuracy = 0.6663
  Batch 270: Loss = 0.6187, Accuracy = 0.6657
  Batch 280: Loss = 0.6217, Accuracy = 0.6652
  Batch 290: Loss = 0.6236, Accuracy = 0.6612
  Batch 300: Loss = 0.6220, Accuracy = 0.6625
  Batch 310: Loss = 0.6211, Accuracy = 0.6629
  Batch 320: Loss = 0.6222, Accuracy = 0.6625

Epoch 2 Summary:
  Train Loss: 0.6235, Train Accuracy: 0.6623
  Test Loss: 13.2208, Test Accuracy: 0.7156

Epoch 3/5
  Batch 10: Loss = 0.5025, Accuracy = 0.7750
  Batch 20: Loss = 0.5908, Accuracy = 0.6625
  Batch 30: Loss = 0.6404, Accuracy = 0.6833
  Batch 40: Loss = 0.6490, Accuracy = 0.6625
  Batch 50: Loss = 0.6654, Accuracy = 0.6600
  Batch 60: Loss = 0.6788, Accuracy = 0.6375
  Batch 70: Loss = 0.6653, Accuracy = 0.6571
  Batch 80: Loss = 0.6627, Accuracy = 0.6687
  Batch 90: Loss = 0.6621, Accuracy = 0.6694
  Batch 100: Loss = 0.6667, Accuracy = 0.6650
  Batch 110: Loss = 0.6718, Accuracy = 0.6591
  Batch 120: Loss = 0.6667, Accuracy = 0.6667
  Batch 130: Loss = 0.6706, Accuracy = 0.6635
  Batch 140: Loss = 0.6601, Accuracy = 0.6750
  Batch 150: Loss = 0.6614, Accuracy = 0.6733
  Batch 160: Loss = 0.6664, Accuracy = 0.6625
  Batch 170: Loss = 0.6693, Accuracy = 0.6603
  Batch 180: Loss = 0.6686, Accuracy = 0.6597
  Batch 190: Loss = 0.6654, Accuracy = 0.6671
  Batch 200: Loss = 0.6591, Accuracy = 0.6725
  Batch 210: Loss = 0.6633, Accuracy = 0.6714
  Batch 220: Loss = 0.6623, Accuracy = 0.6727
  Batch 230: Loss = 0.6584, Accuracy = 0.6739
  Batch 240: Loss = 0.6540, Accuracy = 0.6771
  Batch 250: Loss = 0.6544, Accuracy = 0.6770
  Batch 260: Loss = 0.6574, Accuracy = 0.6740
  Batch 270: Loss = 0.6602, Accuracy = 0.6704
  Batch 280: Loss = 0.6598, Accuracy = 0.6696
  Batch 290: Loss = 0.6568, Accuracy = 0.6716
  Batch 300: Loss = 0.6534, Accuracy = 0.6742
  Batch 310: Loss = 0.6523, Accuracy = 0.6734
  Batch 320: Loss = 0.6506, Accuracy = 0.6758

Epoch 3 Summary:
  Train Loss: 0.6523, Train Accuracy: 0.6753
  Test Loss: 21.9075, Test Accuracy: 0.7003

Epoch 4/5
  Batch 10: Loss = 0.6318, Accuracy = 0.7250
  Batch 20: Loss = 0.6552, Accuracy = 0.7000
  Batch 30: Loss = 0.6538, Accuracy = 0.7000
  Batch 40: Loss = 0.6660, Accuracy = 0.6750
  Batch 50: Loss = 0.6325, Accuracy = 0.7000
  Batch 60: Loss = 0.6416, Accuracy = 0.6792
  Batch 70: Loss = 0.6183, Accuracy = 0.6964
  Batch 80: Loss = 0.6103, Accuracy = 0.7031
  Batch 90: Loss = 0.6112, Accuracy = 0.7083
  Batch 100: Loss = 0.6121, Accuracy = 0.7075
  Batch 110: Loss = 0.6109, Accuracy = 0.7045
  Batch 120: Loss = 0.6104, Accuracy = 0.7063
  Batch 130: Loss = 0.6132, Accuracy = 0.7038
  Batch 140: Loss = 0.6049, Accuracy = 0.7071
  Batch 150: Loss = 0.6090, Accuracy = 0.7000
  Batch 160: Loss = 0.6237, Accuracy = 0.6891
  Batch 170: Loss = 0.6226, Accuracy = 0.6912
  Batch 180: Loss = 0.6216, Accuracy = 0.6917
  Batch 190: Loss = 0.6167, Accuracy = 0.6947
  Batch 200: Loss = 0.6159, Accuracy = 0.6963
  Batch 210: Loss = 0.6167, Accuracy = 0.6964
  Batch 220: Loss = 0.6152, Accuracy = 0.6977
  Batch 230: Loss = 0.6176, Accuracy = 0.6967
  Batch 240: Loss = 0.6147, Accuracy = 0.6979
  Batch 250: Loss = 0.6188, Accuracy = 0.6930
  Batch 260: Loss = 0.6213, Accuracy = 0.6894
  Batch 270: Loss = 0.6227, Accuracy = 0.6870
  Batch 280: Loss = 0.6226, Accuracy = 0.6857
  Batch 290: Loss = 0.6240, Accuracy = 0.6810
  Batch 300: Loss = 0.6214, Accuracy = 0.6833
  Batch 310: Loss = 0.6204, Accuracy = 0.6831
  Batch 320: Loss = 0.6202, Accuracy = 0.6820

Epoch 4 Summary:
  Train Loss: 0.6212, Train Accuracy: 0.6830
  Test Loss: 26.5855, Test Accuracy: 0.4465

Epoch 5/5
  Batch 10: Loss = 0.5350, Accuracy = 0.7750
  Batch 20: Loss = 0.5815, Accuracy = 0.7000
  Batch 30: Loss = 0.5918, Accuracy = 0.7250
  Batch 40: Loss = 0.5990, Accuracy = 0.7188
  Batch 50: Loss = 0.5795, Accuracy = 0.7300
  Batch 60: Loss = 0.6061, Accuracy = 0.7083
  Batch 70: Loss = 0.5827, Accuracy = 0.7214
  Batch 80: Loss = 0.5813, Accuracy = 0.7219
  Batch 90: Loss = 0.5896, Accuracy = 0.7139
  Batch 100: Loss = 0.5856, Accuracy = 0.7175
  Batch 110: Loss = 0.5873, Accuracy = 0.7182
  Batch 120: Loss = 0.5887, Accuracy = 0.7146
  Batch 130: Loss = 0.5956, Accuracy = 0.7077
  Batch 140: Loss = 0.5858, Accuracy = 0.7196
  Batch 150: Loss = 0.5870, Accuracy = 0.7150
  Batch 160: Loss = 0.5916, Accuracy = 0.7078
  Batch 170: Loss = 0.5953, Accuracy = 0.7044
  Batch 180: Loss = 0.6022, Accuracy = 0.7000
  Batch 190: Loss = 0.5967, Accuracy = 0.7066
  Batch 200: Loss = 0.5956, Accuracy = 0.7100
  Batch 210: Loss = 0.5978, Accuracy = 0.7060
  Batch 220: Loss = 0.5983, Accuracy = 0.7080
  Batch 230: Loss = 0.5998, Accuracy = 0.7065
  Batch 240: Loss = 0.5970, Accuracy = 0.7073
  Batch 250: Loss = 0.6021, Accuracy = 0.7010
  Batch 260: Loss = 0.6068, Accuracy = 0.6942
  Batch 270: Loss = 0.6088, Accuracy = 0.6917
  Batch 280: Loss = 0.6119, Accuracy = 0.6884
  Batch 290: Loss = 0.6128, Accuracy = 0.6871
  Batch 300: Loss = 0.6119, Accuracy = 0.6867
  Batch 310: Loss = 0.6123, Accuracy = 0.6855
  Batch 320: Loss = 0.6117, Accuracy = 0.6867

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 5 Summary:
  Train Loss: 0.6123, Train Accuracy: 0.6845
  Test Loss: 8.3640, Test Accuracy: 0.7156
Displaying predictions...
End.